FROM python:3.10-slim

WORKDIR /src

COPY ./src /src
COPY requirements.txt /src

RUN pip install --no-cache-dir --upgrade pip -r requirements.txt

# Return to the working directory
WORKDIR /src

EXPOSE 8002

ENV STREAMLIT_SERVER_PORT=8002

ENV GDAL_CACHEMAX=200
ENV GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
ENV GDAL_HTTP_MULTIPLEX=YES
ENV GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
ENV GDAL_BAND_BLOCK_CACHE=HASHSET
ENV GDAL_HTTP_MAX_RETRY=4
ENV GDAL_HTTP_RETRY_DELAY="0.42"
ENV CPL_VSIL_CURL_ALLOWED_EXTENSIONS=".tif,.TIF,.tiff"
ENV CPL_VSIL_CURL_CACHE_SIZE=200000000
ENV VSI_CACHE=TRUE
ENV VSI_CACHE_SIZE=5000000
ENV GDAL_HTTP_VERSION=2
ENV PROJ_NETWORK=OFF

CMD ["streamlit", "run", "main.py"]
