mapbiomas_classes = {
    1: {"hex_color": "#32a65e","class_type": "Mosaico" ,"class_name": "Floresta"},
    3: {"hex_color": "#1f8d49","class_type": "Natural" ,"class_name": "Formação Florestal"},
    4: {"hex_color": "#7dc975","class_type": "Natural" ,"class_name": "Formação Savânica"},
    5: {"hex_color": "#04381d","class_type": "Natural" ,"class_name": "Mangue"},
    6: {"hex_color": "#026975","class_type": "Natural" ,"class_name": "Floresta Alagável"},
    49: {"hex_color": "#02d659","class_type": "Natural" ,"class_name": "Restinga Arbórea "},

    10: {"hex_color": "#ad975a","class_type": "Natural" ,"class_name": "Formação Natural não Florestal"},
    11: {"hex_color": "#519799","class_type": "Natural" ,"class_name": "Campo Alagado e Área Pantanosa"},
    12: {"hex_color": "#d6bc74","class_type": "Natural" ,"class_name": "Formação Campestre"},
    32: {"hex_color": "#fc8114","class_type": "Natural" ,"class_name": "Apicum"},
    29: {"hex_color": "#ffaa5f","class_type": "Natural" ,"class_name": "Afloramento Rochoso"},
    50: {"hex_color": "#ad5100","class_type": "Natural" ,"class_name": "Restinga Herbácea"},
    13: {"hex_color": "#d89f5c","class_type": "Natural" ,"class_name": "Outras Formações não Florestais"},

    14: {"hex_color": "#FFFFB2","class_type": "Antrópico" ,"class_name": "Agropecuária"},
    15: {"hex_color": "#edde8e","class_type": "Antrópico" ,"class_name": "Pastagem"},
    18: {"hex_color": "#E974ED","class_type": "Antrópico" ,"class_name": "Agricultura"},
    19: {"hex_color": "#C27BA0","class_type": "Antrópico" ,"class_name": "Lavoura Temporária"},
    39: {"hex_color": "#f5b3c8","class_type": "Antrópico" ,"class_name": "Soja"},
    20: {"hex_color": "#db7093","class_type": "Antrópico" ,"class_name": "Cana"},
    40: {"hex_color": "#c71585","class_type": "Antrópico" ,"class_name": "Arroz"},
    62: {"hex_color": "#ff69b4","class_type": "Antrópico" ,"class_name": "Algodão"},
    41: {"hex_color": "#f54ca9","class_type": "Antrópico" ,"class_name": "Outras Lavouras Temporárias"},
    36: {"hex_color": "#d082de","class_type": "Antrópico" ,"class_name": "Lavoura Perene"},
    46: {"hex_color": "#d68fe2","class_type": "Antrópico" ,"class_name": "Café"},
    47: {"hex_color": "#9932cc","class_type": "Antrópico" ,"class_name": "Citrus"},
    35: {"hex_color": "#9065d0","class_type": "Antrópico" ,"class_name": "Dendê"},
    48: {"hex_color": "#e6ccff","class_type": "Antrópico" ,"class_name": "Outras Lavouras Perenes"},
    9: {"hex_color": "#7a5900","class_type": "Antrópico" ,"class_name": "Floresta Plantada"},
    21: {"hex_color": "#ffefc3","class_type": "Antrópico" ,"class_name": "Mosaico de Usos"},

    22: {"hex_color": "#d4271e","class_type": "Mosaico" ,"class_name": "Área não Vegetada"},
    23: {"hex_color": "#ffa07a","class_type": "Natural" ,"class_name": "Praia, Duna e Areal"},
    24: {"hex_color": "#d4271e","class_type": "Antrópico" ,"class_name": "Área Urbanizada"},
    30: {"hex_color": "#9c0027","class_type": "Antrópico" ,"class_name": "Mineração"},
    25: {"hex_color": "#db4d4f","class_type": "Mosaico" ,"class_name": "Outras Áreas não Vegetadas"},

    26: {"hex_color": "#0000FF","class_type": "Mosaico" ,"class_name": "Corpo D'água"},
    33: {"hex_color": "#2532e4","class_type": "Natural" ,"class_name": "Rio, Lago e Oceano"},
    31: {"hex_color": "#091077","class_type": "Antrópico" ,"class_name": "Aquicultura"},

    27: {"hex_color": "#ffffff","class_type": "não observado" ,"class_name": "Não observado"},
}